name: Check Commit Message Format

on:
  push:
    branches:    # Runs on all branches
      - "**"
  pull_request:
    branches:    # Checks pull requests for all branches
      - "**"

jobs:
  commit-message-check:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Run the commit message check
      - name: Validate commit messages
        run: |
          # Retrieve the latest commit message
          commit_message=$(git log -1 --pretty=%s)

          # Validate the commit message format
          if [[ ! "$commit_message" =~ ^HOT[0-9]+:\ [A-Z] ]]; then
              echo "❌ Invalid commit message: '$commit_message'"
              echo "Commit message must follow the format: 'HOT<issue-number>: <Capitalized description>'"
              exit 1
          fi

          echo "✅ Commit message is valid: '$commit_message'"
        shell: bash
