name: Check Commit Message Format

on: push

jobs:
  commit-message-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check commit message format
      run: |
        commits=$(git log --format=%s -n 1 ${GITHUB_SHA})
        for commit in $commits; do
          if [[ ! $commit =~ ^HOT[0-9]+: ]]; then
            echo "❌ Invalid commit message: $commit"
            echo "Commit message must follow the format: 'HOT<issue-number>: <Capitalized description>'"
            exit 1
          fi
        done
        echo "✅ All commit messages follow the required format."
      shell: bash
